export type FlowDept =
  | "core"
  | "executive"
  | "hr"
  | "procurement"
  | "accounting"
  | "warehouse"
  | "marketing"
  | "creative"
  | "store"
  | "interior"
  | "technology";

export interface CompanyFlowNode {
  id: string;
  c: number;
  r: number;
  dept: FlowDept;
  title: string;
  subtitle: string;
  owner: string;
  bullets: string[];
  href?: string;
}

export interface CompanyFlowEdge {
  from: string;
  to: string;
  label: string;
}

export const FLOW_CELL_X = 220;
export const FLOW_CELL_Y = 112;

export const flowDeptMeta: Record<FlowDept, { label: string; color: string; soft: string }> = {
  core: { label: "ระบบกลาง", color: "#111827", soft: "#f1f5f9" },
  executive: { label: "ผู้บริหาร", color: "#7c3aed", soft: "#f5f3ff" },
  hr: { label: "HR / People", color: "#d4a017", soft: "#fffbeb" },
  procurement: { label: "จัดซื้อ", color: "#ea580c", soft: "#fff7ed" },
  accounting: { label: "บัญชี / การเงิน", color: "#e11d48", soft: "#fff1f2" },
  warehouse: { label: "คลัง / Logistics", color: "#059669", soft: "#ecfdf5" },
  marketing: { label: "Marketing", color: "#db2777", soft: "#fdf2f8" },
  creative: { label: "Creative / Graphic", color: "#2563eb", soft: "#eff6ff" },
  store: { label: "Offline / VM / หน้าร้าน", color: "#0f766e", soft: "#f0fdfa" },
  interior: { label: "Interior Design", color: "#9333ea", soft: "#faf5ff" },
  technology: { label: "IT / Dev", color: "#475569", soft: "#f8fafc" },
};

export const companyFlowNodes: CompanyFlowNode[] = [
  {
    id: "employee-portal",
    c: 0,
    r: 4,
    dept: "core",
    title: "Employee Portal",
    subtitle: "หน้าหลักที่พนักงานทุกแผนกใช้",
    owner: "พนักงานทุกคน",
    bullets: ["เปิดการ์ดงาน", "ดูงานของฉัน", "ส่งคำขอ / แนบไฟล์", "ติดตามสถานะและแจ้งเตือน"],
  },
  {
    id: "work-cards",
    c: 2,
    r: 4,
    dept: "core",
    title: "การ์ดงานกลาง",
    subtitle: "แกนหลักของ workflow บริษัท",
    owner: "ทุกแผนก / หัวหน้างาน",
    href: "/work-orders",
    bullets: ["มอบหมายงานข้ามแผนก", "Comment / mention / checklist", "Due date / priority / reviewer", "Activity log ทุกการเปลี่ยนแปลง"],
  },
  {
    id: "approval-hub",
    c: 4,
    r: 4,
    dept: "core",
    title: "Approval Hub",
    subtitle: "ศูนย์อนุมัติรวม",
    owner: "หัวหน้า / ผู้บริหาร / บัญชี",
    bullets: ["อนุมัติลา OT เบิก ขอซื้อ", "Approval matrix ตามวงเงิน", "Request more info / reject พร้อมเหตุผล", "เก็บ audit log"],
  },
  {
    id: "notification",
    c: 6,
    r: 4,
    dept: "core",
    title: "Notification",
    subtitle: "แจ้งเตือนงานและคำขอ",
    owner: "ระบบกลาง",
    bullets: ["งานใหม่ / mention", "ใกล้ deadline / overdue", "รอตรวจ / ถูก reject", "ต่อยอด Email หรือ LINE ได้"],
  },
  {
    id: "master-data",
    c: 2,
    r: 1,
    dept: "core",
    title: "Master Data",
    subtitle: "คน แผนก สาขา ตำแหน่ง สิทธิ์",
    owner: "HR / Admin",
    href: "/employees",
    bullets: ["Employee / Department / Branch", "Role & Permission", "Cost center / job level", "ใช้เป็นฐาน assign งานและอนุมัติ"],
  },
  {
    id: "executive-dashboard",
    c: 8,
    r: 1,
    dept: "executive",
    title: "Executive Dashboard",
    subtitle: "ภาพรวมบริษัทสำหรับตัดสินใจ",
    owner: "ผู้บริหาร",
    href: "/dashboard",
    bullets: ["KPI ทุกแผนก", "งานเสี่ยง / งานเกินกำหนด", "งบ / ยอดขาย / stock risk", "Project portfolio"],
  },
  {
    id: "executive-approval",
    c: 8,
    r: 3,
    dept: "executive",
    title: "Executive Approval",
    subtitle: "รายการที่ต้องตัดสินใจระดับสูง",
    owner: "ผู้บริหาร",
    bullets: ["งบใหญ่ / vendor สำคัญ", "เปิดสาขา / renovate", "campaign ใหญ่", "ปรับเงินเดือน / project budget"],
  },
  {
    id: "hr-self-service",
    c: 0,
    r: 0,
    dept: "hr",
    title: "HR Self-Service",
    subtitle: "พนักงานจัดการเรื่อง HR เอง",
    owner: "HR / พนักงาน",
    bullets: ["ขอลา / ขอ OT", "ดูตารางงานและวันลาคงเหลือ", "เอกสารส่วนตัว", "Onboarding / Offboarding"],
  },
  {
    id: "hr-ops",
    c: 0,
    r: 1,
    dept: "hr",
    title: "HR Operations",
    subtitle: "ข้อมูลบุคลากรและรอบงาน HR",
    owner: "HR",
    href: "/employees",
    bullets: ["พนักงาน / สัญญา / เอกสาร", "สรรหา / onboarding", "training / evaluation / OKR", "ส่งข้อมูลเข้า payroll"],
  },
  {
    id: "procurement-pr",
    c: 0,
    r: 8,
    dept: "procurement",
    title: "Purchase Request",
    subtitle: "พนักงานขอซื้อของอย่างมีหลักฐาน",
    owner: "พนักงาน / หัวหน้า",
    href: "/purchase-requests",
    bullets: ["เหตุผลและงบประมาณ", "แนบใบเสนอราคา / screenshot", "เลือก vendor หรือเสนอ vendor ใหม่", "ส่งเข้าคิวจัดซื้อ"],
  },
  {
    id: "procurement-control",
    c: 2,
    r: 8,
    dept: "procurement",
    title: "Vendor & Link Control",
    subtitle: "กัน affiliate / conflict of interest",
    owner: "จัดซื้อ",
    bullets: ["Vendor master / blacklist", "Affiliate link detector", "URL sanitizer", "Declaration ผลประโยชน์ทับซ้อน"],
  },
  {
    id: "procurement-po",
    c: 4,
    r: 8,
    dept: "procurement",
    title: "PO / Sourcing",
    subtitle: "เปรียบเทียบราคาและออกคำสั่งซื้อ",
    owner: "จัดซื้อ",
    bullets: ["ขอ 2-3 quote ตามวงเงิน", "เลือก vendor สุดท้ายโดยจัดซื้อ", "ออก PO", "ส่งต่อคลังรับของและบัญชีเตรียมจ่าย"],
  },
  {
    id: "accounting-docs",
    c: 6,
    r: 7,
    dept: "accounting",
    title: "Accounting Review",
    subtitle: "ตรวจงบ เอกสาร และภาษี",
    owner: "บัญชี",
    href: "/expenses",
    bullets: ["ใบกำกับ / ใบเสร็จ / invoice", "VAT / WHT / cost center", "เอกสารครบหรือ reject", "ตั้งรอบจ่ายเงิน"],
  },
  {
    id: "accounting-pay",
    c: 8,
    r: 7,
    dept: "accounting",
    title: "Payment & Budget",
    subtitle: "จ่ายเงินและคุมงบ",
    owner: "บัญชี / การเงิน",
    href: "/payroll",
    bullets: ["Payment request vendor", "เบิกค่าใช้จ่าย / petty cash", "Budget actual vs committed", "Export เข้าโปรแกรมบัญชี"],
  },
  {
    id: "warehouse-inventory",
    c: 6,
    r: 10,
    dept: "warehouse",
    title: "Inventory Control",
    subtitle: "ของมีเท่าไร อยู่ตรงไหน",
    owner: "คลัง",
    href: "/inventory",
    bullets: ["SKU / location / bin", "รับเข้า / จ่ายออก", "stock count / adjustment", "reorder alert"],
  },
  {
    id: "warehouse-fulfillment",
    c: 8,
    r: 10,
    dept: "warehouse",
    title: "Picking / Transfer",
    subtitle: "แพ็ก ส่ง และโอนย้าย",
    owner: "คลัง / Logistics",
    href: "/warehouse-3d",
    bullets: ["Picking list / packing list", "ส่งของไปสาขาหรือ event", "Shipment tracking", "POD / ผู้รับยืนยัน"],
  },
  {
    id: "marketing-campaign",
    c: 10,
    r: 0,
    dept: "marketing",
    title: "Campaign Workspace",
    subtitle: "แผน campaign และ budget",
    owner: "Marketing",
    href: "/campaigns",
    bullets: ["Campaign brief / KPI", "Budget tracking", "Promotion setup", "Post-campaign report"],
  },
  {
    id: "marketing-calendar",
    c: 10,
    r: 2,
    dept: "marketing",
    title: "Content Calendar",
    subtitle: "แผนปล่อยสื่อทุกช่องทาง",
    owner: "Marketing",
    bullets: ["Facebook / IG / TikTok / LINE", "Scheduled / published", "UTM / tracking link", "Performance dashboard"],
  },
  {
    id: "creative-idea",
    c: 12,
    r: 0,
    dept: "creative",
    title: "Idea & Direction",
    subtitle: "ต้นน้ำของแคมเปญ",
    owner: "Creative",
    bullets: ["Idea board / moodboard", "Key message / tagline", "Tone of voice", "Creative direction"],
  },
  {
    id: "graphic-production",
    c: 12,
    r: 2,
    dept: "creative",
    title: "Design Production",
    subtitle: "บรีฟ ออกแบบ แก้แบบ ส่งไฟล์",
    owner: "Graphic",
    bullets: ["Creative brief", "Version / revision tracking", "Asset library", "Final sign-off"],
  },
  {
    id: "offline-activation",
    c: 10,
    r: 5,
    dept: "store",
    title: "Offline Activation",
    subtitle: "งาน event / pop-up / หน้าร้าน",
    owner: "Offline Team",
    bullets: ["Event brief / calendar", "Checklist ก่อนออกงาน", "Stock & equipment request", "Post-event report"],
  },
  {
    id: "vm-compliance",
    c: 12,
    r: 5,
    dept: "store",
    title: "VM Compliance",
    subtitle: "ตรวจ display และ guideline",
    owner: "VM",
    bullets: ["Planogram / guideline", "Store photo submission", "Audit score", "Correction task"],
  },
  {
    id: "store-staff",
    c: 10,
    r: 8,
    dept: "store",
    title: "Store Staff App",
    subtitle: "หน้าร้านใช้ง่ายบนมือถือ",
    owner: "พนักงานหน้าร้าน",
    href: "/stores",
    bullets: ["My shift / checklist เปิด-ปิดร้าน", "Issue report", "Stock request", "Campaign info / customer feedback"],
  },
  {
    id: "interior-project",
    c: 12,
    r: 8,
    dept: "interior",
    title: "Interior Project",
    subtitle: "สาขาใหม่ / renovate / booth",
    owner: "Interior Design",
    bullets: ["Project workspace", "Site survey", "Drawing / render version", "BOQ / budget tracking"],
  },
  {
    id: "interior-site",
    c: 12,
    r: 10,
    dept: "interior",
    title: "Site / Handover",
    subtitle: "หน้างาน defect และส่งมอบ",
    owner: "Interior / Contractor",
    bullets: ["Punch list / defect photo", "Vendor / contractor", "Timeline / gantt", "Handover package"],
  },
  {
    id: "it-service",
    c: 0,
    r: 12,
    dept: "technology",
    title: "IT Service Desk",
    subtitle: "support พนักงานและสาขา",
    owner: "IT",
    bullets: ["Ticket category / SLA", "Access request", "Device / license asset", "Onboarding / offboarding IT"],
  },
  {
    id: "dev-backlog",
    c: 2,
    r: 12,
    dept: "technology",
    title: "Dev Backlog",
    subtitle: "พัฒนาระบบและ integration",
    owner: "Dev / Engineering",
    bullets: ["Feature request / bug", "Code review / QA / release", "Technical debt", "Integration tracker"],
  },
  {
    id: "incident-release",
    c: 4,
    r: 12,
    dept: "technology",
    title: "Incidents & Releases",
    subtitle: "ดูแล production",
    owner: "IT / Dev",
    bullets: ["ระบบล่ม / hotfix", "Root cause / postmortem", "Release notes", "Rollback plan"],
  },
  {
    id: "reports",
    c: 8,
    r: 12,
    dept: "core",
    title: "Reports",
    subtitle: "รายงานรวมจากทุกแผนก",
    owner: "ผู้บริหาร / หัวหน้า",
    href: "/reports",
    bullets: ["Executive summary", "Department KPI", "Budget / stock / campaign", "Approval bottleneck"],
  },
];

export const companyFlowEdges: CompanyFlowEdge[] = [
  { from: "employee-portal", to: "work-cards", label: "เปิดงาน / ติดตามงาน" },
  { from: "master-data", to: "work-cards", label: "คน แผนก สิทธิ์" },
  { from: "work-cards", to: "approval-hub", label: "งานที่ต้องอนุมัติ" },
  { from: "approval-hub", to: "notification", label: "แจ้งผล / ทวง action" },
  { from: "notification", to: "employee-portal", label: "กลับไปทำงานต่อ" },
  { from: "work-cards", to: "executive-dashboard", label: "สรุปงานและความเสี่ยง" },
  { from: "approval-hub", to: "executive-approval", label: "วงเงินสูง / เรื่องสำคัญ" },
  { from: "executive-approval", to: "executive-dashboard", label: "decision log" },
  { from: "hr-self-service", to: "approval-hub", label: "ลา / OT / เอกสาร" },
  { from: "hr-ops", to: "master-data", label: "ข้อมูลพนักงานจริง" },
  { from: "hr-ops", to: "accounting-pay", label: "payroll input" },
  { from: "employee-portal", to: "procurement-pr", label: "ขอซื้อของ" },
  { from: "procurement-pr", to: "procurement-control", label: "ตรวจ vendor / affiliate" },
  { from: "procurement-control", to: "approval-hub", label: "flag เสี่ยง / ขออนุมัติ" },
  { from: "approval-hub", to: "procurement-po", label: "อนุมัติแล้วออก PO" },
  { from: "procurement-po", to: "warehouse-inventory", label: "รับของเข้า stock" },
  { from: "procurement-po", to: "accounting-docs", label: "invoice / PO / vendor" },
  { from: "accounting-docs", to: "accounting-pay", label: "เอกสารครบ → จ่าย" },
  { from: "accounting-pay", to: "reports", label: "งบและ cash outflow" },
  { from: "warehouse-inventory", to: "warehouse-fulfillment", label: "หยิบ แพ็ก โอนย้าย" },
  { from: "warehouse-inventory", to: "procurement-pr", label: "stock ต่ำ → ขอซื้อ" },
  { from: "warehouse-fulfillment", to: "store-staff", label: "ส่งของไปสาขา" },
  { from: "marketing-campaign", to: "creative-idea", label: "บรีฟ concept" },
  { from: "creative-idea", to: "graphic-production", label: "แตกงานผลิต asset" },
  { from: "graphic-production", to: "marketing-calendar", label: "ส่ง asset final" },
  { from: "marketing-calendar", to: "offline-activation", label: "แคมเปญหน้าร้าน / event" },
  { from: "marketing-campaign", to: "approval-hub", label: "budget / promotion approval" },
  { from: "offline-activation", to: "warehouse-fulfillment", label: "ขอ stock / อุปกรณ์" },
  { from: "offline-activation", to: "vm-compliance", label: "display guideline" },
  { from: "vm-compliance", to: "store-staff", label: "ให้สาขาถ่ายรูปส่ง / แก้ display" },
  { from: "store-staff", to: "work-cards", label: "issue / stock request / feedback" },
  { from: "store-staff", to: "marketing-campaign", label: "ยอดขายและ feedback" },
  { from: "interior-project", to: "approval-hub", label: "อนุมัติแบบ / BOQ / งบ" },
  { from: "interior-project", to: "procurement-pr", label: "วัสดุ / fixture / contractor" },
  { from: "interior-project", to: "offline-activation", label: "พื้นที่ event / pop-up" },
  { from: "interior-site", to: "work-cards", label: "defect / punch list" },
  { from: "interior-site", to: "store-staff", label: "handover ให้สาขา" },
  { from: "it-service", to: "work-cards", label: "ticket เป็นการ์ดงาน" },
  { from: "it-service", to: "master-data", label: "account / access ตาม role" },
  { from: "dev-backlog", to: "work-cards", label: "feature / bug / sprint task" },
  { from: "dev-backlog", to: "incident-release", label: "deploy / release" },
  { from: "incident-release", to: "notification", label: "แจ้ง outage / release" },
  { from: "incident-release", to: "executive-dashboard", label: "incident สำคัญ" },
  { from: "reports", to: "executive-dashboard", label: "KPI รวม" },
];
