export type EmployeeStatus = "active" | "inactive" | "on_leave";

export interface MockEmployee {
  id: string;
  code: string;
  firstName: string;
  lastName: string;
  fullName: string;
  departmentId: string;
  departmentName: string;
  branchId: string;
  branchName: string;
  positionName: string;
  jobLevel: string;
  avatarInitials: string;
  status: EmployeeStatus;
  phone: string;
  email: string;
  startDate: string;
  gender: "male" | "female";
}

export const mockEmployees: MockEmployee[] = [
  { id: "emp-1",  code: "EMP-001", firstName: "ปวิตร",     lastName: "วงศ์สุวรรณ", fullName: "ปวิตร วงศ์สุวรรณ",     departmentId: "dept-1", departmentName: "บริหาร",            branchId: "br-1", branchName: "HQ",           positionName: "CEO",                  jobLevel: "C-Level",     avatarInitials: "ปว", status: "active",   phone: "081-000-0001", email: "pawit@senseasia.com",      startDate: "2020-01-10", gender: "male"   },
  { id: "emp-2",  code: "EMP-002", firstName: "อรรถพล",    lastName: "รุ่งเรือง",   fullName: "อรรถพล รุ่งเรือง",      departmentId: "dept-1", departmentName: "บริหาร",            branchId: "br-1", branchName: "HQ",           positionName: "Operations Manager",   jobLevel: "Manager",     avatarInitials: "อพ", status: "active",   phone: "081-000-0002", email: "atthaphon@senseasia.com",  startDate: "2020-03-15", gender: "male"   },
  { id: "emp-3",  code: "EMP-003", firstName: "สมชาย",     lastName: "ใจดี",        fullName: "สมชาย ใจดี",           departmentId: "dept-6", departmentName: "HR",                branchId: "br-1", branchName: "HQ",           positionName: "HR Manager",           jobLevel: "Manager",     avatarInitials: "สช", status: "active",   phone: "081-000-0003", email: "somchai@senseasia.com",    startDate: "2020-06-01", gender: "male"   },
  { id: "emp-4",  code: "EMP-004", firstName: "พัชรี",     lastName: "สุขสวัสดิ์",  fullName: "พัชรี สุขสวัสดิ์",      departmentId: "dept-6", departmentName: "HR",                branchId: "br-1", branchName: "HQ",           positionName: "HR Officer",           jobLevel: "Mid-Level",   avatarInitials: "พช", status: "active",   phone: "081-000-0004", email: "patcharee@senseasia.com",  startDate: "2021-02-01", gender: "female" },
  { id: "emp-5",  code: "EMP-005", firstName: "วิภาวี",    lastName: "คงดี",        fullName: "วิภาวี คงดี",           departmentId: "dept-5", departmentName: "บัญชี",             branchId: "br-1", branchName: "HQ",           positionName: "Finance Manager",      jobLevel: "Manager",     avatarInitials: "วภ", status: "active",   phone: "081-000-0005", email: "wipawi@senseasia.com",     startDate: "2020-09-01", gender: "female" },
  { id: "emp-6",  code: "EMP-006", firstName: "ณัฐพล",     lastName: "มีสุข",       fullName: "ณัฐพล มีสุข",           departmentId: "dept-5", departmentName: "บัญชี",             branchId: "br-1", branchName: "HQ",           positionName: "Accountant",           jobLevel: "Mid-Level",   avatarInitials: "ณพ", status: "active",   phone: "081-000-0006", email: "natthapon@senseasia.com",  startDate: "2021-05-10", gender: "male"   },
  { id: "emp-7",  code: "EMP-007", firstName: "อรทัย",     lastName: "พิมพ์ใจ",     fullName: "อรทัย พิมพ์ใจ",         departmentId: "dept-2", departmentName: "IT",                branchId: "br-1", branchName: "HQ",           positionName: "IT Manager",           jobLevel: "Manager",     avatarInitials: "อท", status: "active",   phone: "081-000-0007", email: "orathai@senseasia.com",    startDate: "2020-11-01", gender: "female" },
  { id: "emp-8",  code: "EMP-008", firstName: "ธนกร",      lastName: "ช่างคิด",     fullName: "ธนกร ช่างคิด",          departmentId: "dept-2", departmentName: "IT",                branchId: "br-1", branchName: "HQ",           positionName: "IT Support",           jobLevel: "Junior",      avatarInitials: "ธก", status: "active",   phone: "081-000-0008", email: "thanakorn@senseasia.com",  startDate: "2022-01-15", gender: "male"   },
  { id: "emp-9",  code: "EMP-009", firstName: "ศิริ",      lastName: "สร้างสรรค์",  fullName: "ศิริ สร้างสรรค์",       departmentId: "dept-8", departmentName: "Creative & Marketing", branchId: "br-1", branchName: "HQ",       positionName: "Creative Director",    jobLevel: "Director",    avatarInitials: "ศร", status: "active",   phone: "081-000-0009", email: "siri@senseasia.com",       startDate: "2020-07-01", gender: "female" },
  { id: "emp-10", code: "EMP-010", firstName: "พิมพ์ใจ",   lastName: "สวยงาม",      fullName: "พิมพ์ใจ สวยงาม",        departmentId: "dept-8", departmentName: "Creative & Marketing", branchId: "br-2", branchName: "Siam Square", positionName: "Marketing Executive",  jobLevel: "Mid-Level",   avatarInitials: "พจ", status: "active",   phone: "081-000-0010", email: "pimjai@senseasia.com",     startDate: "2021-08-01", gender: "female" },
  { id: "emp-11", code: "EMP-011", firstName: "พิชัย",     lastName: "ออกแบบ",      fullName: "พิชัย ออกแบบ",          departmentId: "dept-3", departmentName: "Interior",          branchId: "br-1", branchName: "HQ",           positionName: "Interior Designer",    jobLevel: "Senior",      avatarInitials: "พช", status: "on_leave", phone: "081-000-0011", email: "pichai@senseasia.com",     startDate: "2021-03-01", gender: "male"   },
  { id: "emp-12", code: "EMP-012", firstName: "รัตนา",     lastName: "แฟชั่น",      fullName: "รัตนา แฟชั่น",          departmentId: "dept-9", departmentName: "Design",            branchId: "br-1", branchName: "HQ",           positionName: "Fashion Designer",     jobLevel: "Senior",      avatarInitials: "รน", status: "active",   phone: "081-000-0012", email: "rattana@senseasia.com",    startDate: "2021-01-15", gender: "female" },
  { id: "emp-13", code: "EMP-013", firstName: "ปรีชา",     lastName: "สต็อกดี",     fullName: "ปรีชา สต็อกดี",         departmentId: "dept-7", departmentName: "สต๊อก",             branchId: "br-8", branchName: "Warehouse",    positionName: "Stock Manager",        jobLevel: "Manager",     avatarInitials: "ปช", status: "active",   phone: "081-000-0013", email: "preecha@senseasia.com",    startDate: "2020-12-01", gender: "male"   },
  { id: "emp-14", code: "EMP-014", firstName: "วิชัย",     lastName: "จัดหา",       fullName: "วิชัย จัดหา",           departmentId: "dept-4", departmentName: "จัดซื้อ",           branchId: "br-1", branchName: "HQ",           positionName: "Purchasing Officer",   jobLevel: "Mid-Level",   avatarInitials: "วช", status: "active",   phone: "081-000-0014", email: "wichai@senseasia.com",     startDate: "2021-09-01", gender: "male"   },
  { id: "emp-15", code: "EMP-015", firstName: "ธีรภัทร",   lastName: "ขายเก่ง",     fullName: "ธีรภัทร ขายเก่ง",       departmentId: "dept-10", departmentName: "ขาย",              branchId: "br-2", branchName: "Siam Square",  positionName: "Sales Manager",        jobLevel: "Manager",     avatarInitials: "ธภ", status: "active",   phone: "081-000-0015", email: "teeraphath@senseasia.com", startDate: "2020-10-01", gender: "male"   },
  { id: "emp-16", code: "EMP-016", firstName: "กานต์",     lastName: "ดีใจ",        fullName: "กานต์ ดีใจ",            departmentId: "dept-10", departmentName: "ขาย",              branchId: "br-3", branchName: "Siam Center",  positionName: "Sales Officer",        jobLevel: "Junior",      avatarInitials: "กด", status: "active",   phone: "081-000-0016", email: "karn@senseasia.com",       startDate: "2022-06-01", gender: "female" },
  { id: "emp-17", code: "EMP-017", firstName: "มณี",       lastName: "ส่องแสง",     fullName: "มณี ส่องแสง",           departmentId: "dept-10", departmentName: "ขาย",              branchId: "br-4", branchName: "Mega Bangna",  positionName: "Sales Officer",        jobLevel: "Junior",      avatarInitials: "มณ", status: "active",   phone: "081-000-0017", email: "manee@senseasia.com",      startDate: "2022-09-01", gender: "female" },
  { id: "emp-18", code: "EMP-018", firstName: "ภูวนาท",    lastName: "มั่นคง",      fullName: "ภูวนาท มั่นคง",          departmentId: "dept-7", departmentName: "สต๊อก",             branchId: "br-8", branchName: "Warehouse",    positionName: "Stock Officer",        jobLevel: "Entry Level", avatarInitials: "ภว", status: "active",   phone: "081-000-0018", email: "phuwanat@senseasia.com",   startDate: "2023-01-01", gender: "male"   },
  { id: "emp-19", code: "EMP-019", firstName: "ชลิตา",     lastName: "งามพร้อม",    fullName: "ชลิตา งามพร้อม",        departmentId: "dept-9", departmentName: "Design",            branchId: "br-1", branchName: "HQ",           positionName: "Graphic Designer",     jobLevel: "Mid-Level",   avatarInitials: "ชล", status: "inactive", phone: "081-000-0019", email: "chalita@senseasia.com",    startDate: "2021-11-01", gender: "female" },
  { id: "emp-20", code: "EMP-020", firstName: "ตรีทิพย์",  lastName: "แสนสวย",      fullName: "ตรีทิพย์ แสนสวย",       departmentId: "dept-8", departmentName: "Creative & Marketing", branchId: "br-5", branchName: "Central Rama 9", positionName: "Content Creator",    jobLevel: "Junior",      avatarInitials: "ตท", status: "active",   phone: "081-000-0020", email: "treetip@senseasia.com",    startDate: "2023-03-15", gender: "female" },
  { id: "emp-21", code: "EMP-021", firstName: "อภิสิทธิ์", lastName: "เชี่ยวชาญ",  fullName: "อภิสิทธิ์ เชี่ยวชาญ",   departmentId: "dept-2", departmentName: "IT",                branchId: "br-1", branchName: "HQ",           positionName: "Developer",            jobLevel: "Senior",      avatarInitials: "อส", status: "active",   phone: "081-000-0021", email: "apisit@senseasia.com",     startDate: "2022-04-01", gender: "male"   },
  { id: "emp-22", code: "EMP-022", firstName: "สุนิสา",    lastName: "รักงาน",      fullName: "สุนิสา รักงาน",          departmentId: "dept-4", departmentName: "จัดซื้อ",           branchId: "br-1", branchName: "HQ",           positionName: "Senior Buyer",         jobLevel: "Senior",      avatarInitials: "สน", status: "active",   phone: "081-000-0022", email: "sunisa@senseasia.com",     startDate: "2021-07-01", gender: "female" },
];
